# Generated by Django 4.2.10 on 2025-04-25 16:12

import apps.documents.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('policy', 'Policy'), ('instruction', 'Instruction'), ('regulation', 'Regulation'), ('other', 'Other')], max_length=20)),
                ('signed_at', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='processes.process')),
            ],
        ),
    ]
