# Generated by Django 4.2.10 on 2025-04-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_rel', to='processes.process')),
                ('sub_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_rel', to='processes.process')),
            ],
            options={
                'unique_together': {('process', 'sub_process')},
            },
        ),
    ]
